COMMON: COMMON

NBHome: Home
NBProfile: Profile
NBProjectList: Project list
NBTeamManagement: Team management
NBLogin: Login
NBLogout: Logout


CommonActionMarkState: Marked?
CommonActionMarkButton: Mark
CommonActionEdit: Edit?
CommonActionEditButton: Edit
CommonActionCloseButton: Close
CommonActionSaveButton: Save

CommonAlertNothingShouldBeRemoved: Nothing should be removed.

CommonTextJavascriptDisabled: JavaScript is disabled, please turn it on to enable HITED functionality.

EnglishLanguageOption: English
SwedishLanguageOption: Swedish


HOME: HOME

HomeRTitle: HITED - Health and IT - Experimental Design
HomeRSubtitle: A tool for experimental design of resource sensitive experiments
HomeRIntroductionSection: Introduction
HomeRIntroductionSectionP1: You must log in to get access to the tool.
HomeRIntroductionSectionP2: The tool is developed for Skaraborg's Health Technology Center at University of Skövde within the SIM2020 project.

PREFERENCES: PREFERENCES

ErrorGetPreferences: It was not possible to retrieve the preferences data. The most likely cause is that there is a problem with the server. 

PRIVACYPOLICY: PRIVACYPOLICY

PrivacyPolicyRTitle: Privacy Policy

PROFILE: PROFILE

ProfileRTitle: Access granted.
ProfileIntroductionSectionParagraph: This page is protected and access is allowed only for authenticated users.
ProfileIntroductionSectionParagraph2: Your data is protected with us
ProfilePreferenceHeader: Preferences:
ProfileSettingHeading: Setting
ProfileOptionHeading: Option
ProfileLanguageSetting: Language choice
ProfileErrorChangeLanguageChoice: Incorrect language choice.
ProfileErrorChangeLanguageSetting: It was not possible to change the language.
ProfileChangeLanguageSuccess: Language choice is set.


PROJECT: PROJECT

ActionRegisterProjectButton: Register project
ActionRemoveProjectButton: Remove marked projects

AlertFeedInProjectName: Feed in a project name.

BreadcumbProjectList: Project list

ConfirmRemoveProject: Do you really want to remove the following projects?

ErrorProjectGetProjects: It was not possible to access data about the projects. The most likely cause is that there is a problem with the server.
ErrorProjectGetProjectsInWhichUserOnlyParticipates: It was not possible to access data about the projects in which you only participate. The most likely cause is that there is a problem with the server.
ErrorCreateProject: It was not possible to register the project. The most likely cause is that it already exists or that there is a problem with the server. 
ErrorRemoveProjects: It is not possible to remove marked projects. Either you have associated teams or it is some problem with the server.
ErrorGetAssociatedTeams: It was not possible to find associated teams. The most likely cause is that there is some problem with the server.
ErrorProjectUpdateProject: It was not possible to update the project data. The most likely cause is that is some problem with the server.

ErrorProjectAssociatedTeamAdditionNotSelected: You have not chosen any teams to add to your project.

ErrorProjectAssociatedTeamAdditionError: It was not possible to add the selected teams to the project. It is most likely a problem with the server or that the team has been removed.

ErrorProjectAssociatedTeamRemovalNotSelected: You have not chosen any team to remove from your project.

ErrorProjectAssociatedTeamRemovalError: It was not possible to remove the selected teams from the project. It is most likely a problem with the server or that the team has been removed.

ErrorProjectGetNotInProjectTeams: It was not possible to access data about what teams that are not associated with the project. The most likely cause is there is some problem with the server.
ErrorProjectGetInProjectTeams: It was not possible to access data about what teams that are associated with the project. The most likely cause is there is some problem with the server.


ProjectListRTitle: HITED: Project list

ProjectName: Project name
ProjectOwner: Project owner
ProjectDescription: Project description
ProjectTeam: Project team

ProjectModalEditTitle: Edit project
ProjectModalEditNamePlaceholder: Enter a project name
ProjectModalEditDescriptionPlaceholder: Enter a project description
ProjectModalEditSelect: Currently associated teams 
ProjectModalEditSelectFrom: Potentially associated teams


TEAM: TEAM

ActionRegisterTeamButton: Register team
ActionRemoveTeamButton: Remove marked teams


ConfirmRemoveTeam: Do you really want to remove the following team?

ErrorCreateTeam: It was not possible to register the team. The most likely cause is that it already exists or that there is a problem with the server. 
ErrorGetTeam: It was not possible to retrieve the teams. The most likely cause is that there is a problem with the server. 
ErrorRemoveTeams: It is not possible to remove marked teams.

ErrorTeamUpdateTeam: It was not possible to update the team data. The most likely cause is that is some problem with the server.

ErrorTeamMemberAdditionNotSelected: You have not chosen any users to add to your team.

ErrorTeamMemberAdditionError: It was not possible to add the selected users to the team. It is most likely a problem with the server or that the user has been removed.

ErrorTeamMemberRemovalNotSelected: You have not chosen any users to remove from your team.

ErrorTeamMemberRemovalError: It was not possible to remove the selected users from the team. It is most likely a problem with the server or that the user has been removed.



TeamModalEditTitle: Edit team
TeamModalEditTeamNamePlaceholder: Enter a team name
TeamModalEditTeamDescriptionPlaceholder: Enter a team description
TeamModalEditTeamSelect: Current team members.
TeamModalEditTeamSelectFrom: Potential team members


TeamRTitle: HITED: Team management

TeamName: Team name
TeamOwner: Team owner
TeamDescription: Team description
TeamMember: Team member

TERMSOFSERVICE: TERMSOFSERVICE

TermsOfServiceRTitle: Terms of service

USER: USER

ErrorGetUser: It was not possible to retrieve the user data. The most likely cause is that there is a problem with the server. 
ErrorGetNotInTeamUsers: It was not possible to retrieve data concerning who is not in the team. The most likely cause is that there is a problem with the server.
ErrorGetInTeamUsers: It was not possible to retrieve data concerning who is in the team. The most likely cause is that there is a problem with the server. 