COMMON: COMMON

NBHome: Hem
NBProfile: Profil
NBProjectList: Projekt
NBTeamManagement: Team
NBAdmin: Admin
NBLogin: Logga in
NBLogout: Logga ut
NBEditor: Editor


CommonActionMarkState: Markerad?
CommonActionMarkButton: Markera
CommonActionEdit: Editera?
CommonActionEditButton: Editera
CommonActionCloseButton: Stäng
CommonActionSaveButton: Spara

CommonAlertNothingShouldBeRemoved: Inget ska tas bort.

CommonTextJavascriptDisabled: JavaScript är avstängt, var vänlig och slå på det för att få HITED att fungera. 

EnglishLanguageOption: Engelska
SwedishLanguageOption: Svenska




EDITOR: EDITOR
EditorRTitle: Editor


HOME: HOME

HomeRTitle: HITED - Hälsa och Informationsteknologi - Experimentell Design
HomeRSubtitle: Ett verktyg för experimentell design av resurskänsliga experiment
HomeRIntroductionSection: Introduktion
HomeRIntroductionSectionP1: Du behöver logga in för att få åtkomst till verktyget.
HomeRIntroductionSectionP2: Verktyget är utvecklat för Skaraborgs Hälsoteknikcentrum på Högskolan i Skövde inom ramen för projektet SIM2020.

PREFERENCES: PREFERENCES

ErrorGetPreferences: Det gick inte att få tag i preferensdata. Förmodligen är det något problem med serven.

PRIVACYPOLICY: PRIVACYPOLICY

PrivacyPolicyRTitle: Integritetspolicy

PROFILE: PROFILE

ProfileRTitle: Åtkomst medgiven.
ProfileIntroductionSectionParagraph: Denna sida är skyddad och åtkomst medges endast för autentiserade användare.
ProfileIntroductionSectionParagraph2: Er data är skyddad med oss
ProfilePreferenceHeader: Preferenser:
ProfileSettingHeading: Inställning
ProfileOptionHeading: Val
ProfileLanguageSetting: Språkval
ProfileErrorChangeLanguageChoice: Ej korrekt språkval.
ProfileErrorChangeLanguageSetting: Kunde inte sätta språkvalet.
ProfileChangeLanguageSuccess: Språkval satt.

PROJECT: PROJECT

ActionRegisterProjectButton: Registrera projekt
ActionRemoveProjectButton: Ta bort markerade projekt


AlertFeedInProjectName: Mata in ett projektnamn!

BreadcumbProjectList: Projectlista

ConfirmRemoveProject: Vill du ta bort följande projekt?

ErrorProjectGetProjects: Det gick inte att få tag i data om projekten. Det förmodligen något problem med servern.
ErrorProjectGetProjectsInWhichUserOnlyParticipates: Det gick inte att få tag i data om projekten som du enbart deltar i. Det förmodligen något problem med servern.
ErrorCreateProject: Det gick inte att lägga till projektet. Förmodligen finns det redan eller så det något problem med servern
ErrorRemoveProjects: Det gick inte att ta bort markerade projekt. Det kan bero på att du har associerade team eller att det är något fel på servern.
ErrorGetAssociatedTeams: Det gick inte att hitta associerade team. Förmodligen är det något problem med server.
ErrorProjectUpdateProject: Det gick inte att uppdatera projektdata. Förmodligen är det något problem med servern. 

ErrorProjectAssociatedTeamAdditionNotSelected: Du har inte valt några team som ska läggas till projektet.

ErrorProjectAssociatedTeamAdditionError: Det var inte möjligt att lägga till valda team till projektet. Det mest sannolika skälet är att det är problem med servern eller teamet har tagits bort. 

ErrorProjectAssociatedTeamRemovalNotSelected: Du har inte valt några etam som ska tas bort från projektet. 

ErrorProjectAssociatedTeamRemovalError: Det var inte möjligt att ta bort det valda teamet från projeket. Det mest sannolika skälet är att det är problem med servern eller någon har uppdaterat det valda projektet. 

ErrorProjectGetNotInProjectTeams: Det gick inte att få tag i data om vilka team som inte är associerade i projektet. Förmodligen är det något problem med serven.
ErrorProjectGetInProjectTeams: Det gick inte att få tag i data om vilka team som är associerade med i projektet. Förmodligen är det något problem med serven.


ProjectListRTitle: HITED: Projektlista

ProjectName: Projektnamn
ProjectOwner: Projektägare
ProjectDescription: Projektbeskrivning
ProjectTeam: Projektteam

ProjectModalEditTitle: Editera projekt
ProjectModalEditNamePlaceholder: Mata in ett projektnamn
ProjectModalEditDescriptionPlaceholder: Mata in ett projektbeskrivning
ProjectModalEditSelect: Nuvarande associerade team
ProjectModalEditSelectFrom: Potentiellt associerade team



TEAM: TEAM

ActionRegisterTeamButton: Registrera team
ActionRemoveTeamButton: Ta bort markerade team

ConfirmRemoveTeam: Vill du ta bort följande team?

ErrorCreateTeam: Det gick inte att lägga till teamet. Förmodligen finns det redan eller så det något problem med servern
ErrorGetTeam: Det gick inte att få tag i teamen. Förmodligen är det något problem med serven.
ErrorGetTeamMembers: Det gick inte att få tag i teammedlemmarna. Förmodligen är det något problem med serven.
ErrorRemoveTeams: Det gick inte att ta bort markerade team.

ErrorTeamUpdateTeam: Det gick inte att uppdatera teamdata. Förmodligen är det något problem med servern. 

ErrorTeamMemberAdditionNotSelected: Du har inte valt några användare som ska läggas till.

ErrorTeamMemberAdditionError: Det gick inte att lägga till valda användare i teamet. Det är förmodligen något problem med servern eller så har användaren tagits bort.

ErrorTeamMemberRemovalNotSelected: Du har inte valt några användare som ska tas bort.

ErrorTeamMemberRemovalError: Det gick inte att ta bort valda användare från teamet. Det är förmodligen något problem med servern eller så har användaren tagits bort.



TeamModalEditTitle: Editera team
TeamModalEditTeamNamePlaceholder: Mata in ett teamnamn
TeamModalEditTeamDescriptionPlaceholder: Mata in ett teambeskrivning
TeamModalEditTeamSelect: Nuvarande teammedlemmar
TeamModalEditTeamSelectFrom: Potentiella teammedlemmar



TeamRTitle: HITED: Teamhantering

TeamName: Teamnamn
TeamOwner: Teamägare
TeamDescription: Teambeskrivning
TeamMember: Teammedlem

TERMSOFSERVICE: TERMSOFSERVICE

TermsOfServiceRTitle: Terms of Service

USER: USER

ErrorGetUser: Det gick inte att få tag i användardata. Förmodligen är det något problem med serven.
ErrorGetNotInTeamUsers: Det gick inte att få tag i data om vilka som inte finns med i teamet. Förmodligen är det något problem med serven.
ErrorGetInTeamUsers: Det gick inte att få tag i data om vilka som finns med i teamet. Förmodligen är det något problem med serven.
